version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_container
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www/html
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=chi-attendence-quantum-picks.a.aivencloud.com"
      - "DB_PORT=20931"
      - "DB_DATABASE=attendence"
      - "DB_USERNAME=avnadmin"
      - "DB_PASSWORD=AVNS_3gTCq3EWjEyNKGUOv88"
      -  APP_NAME=Laravel
      -  APP_ENV=production
      -  APP_KEY=base64:JCABD5xDR027pDNkQ0X/JWLihFzxvezBtFJhrXjVkpo=
      -  APP_DEBUG=false
      -  APP_URL=http://localhost
      -  LOG_CHANNEL=stack
      -  LOG_DEPRECATIONS_CHANNEL=null
      -  LOG_LEVEL=debug
      -  BROADCAST_DRIVER=log
      -  CACHE_DRIVER=file
      -  FILESYSTEM_DISK=local
      -  QUEUE_CONNECTION=sync
      -  SESSION_DRIVER=database
      -  SESSION_LIFETIME=120
      -  MEMCACHED_HOST=127.0.0.1
      -  REDIS_HOST=127.0.0.1
      -  REDIS_PASSWORD=null
      -  REDIS_PORT=6379
      -  MAIL_MAILER=smtp
      -  MAIL_HOST=mailpit
      -  MAIL_PORT=1025
      -  MAIL_USERNAME=null
      -  MAIL_PASSWORD=null
      -  MAIL_ENCRYPTION=null
      -  MAIL_FROM_ADDRESS="hello@example.com"
      -  MAIL_FROM_NAME="${APP_NAME}"
      -  AWS_ACCESS_KEY_ID=
      -  AWS_SECRET_ACCESS_KEY=
      -  AWS_DEFAULT_REGION=us-east-1
      -  AWS_BUCKET=
      -  AWS_USE_PATH_STYLE_ENDPOINT=false
      -  PUSHER_APP_ID=
      -  PUSHER_APP_KEY=
      -  PUSHER_APP_SECRET=
      -  PUSHER_HOST=
      -  PUSHER_PORT=443
      -  PUSHER_SCHEME=https
      -  PUSHER_APP_CLUSTER=mt1
      -  VITE_APP_NAME="${APP_NAME}"
      -  VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      -  VITE_PUSHER_HOST="${PUSHER_HOST}"
      -  VITE_PUSHER_PORT="${PUSHER_PORT}"
      -  VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
      -  VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
      -  PASSPORT_PERSONAL_ACCESS_CLIENT_ID="9b5c59f7-4807-443a-8382-23b96c9e129f"
      -  PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET="zvxu7ykT2wtjVI1BgsTBkGmFvF7qdEhk1lU8o738"